from fastapi import FastAPI
from prometheus_client import Counter, generate_latest, CONTENT_TYPE_LATEST
from fastapi.responses import Response

app = FastAPI(
    title="${{ values.name }}",
    description="Generated by the Platform Engineering golden path",
    version="1.0.0",
)

REQUEST_COUNT = Counter(
    "app_requests_total",
    "Total number of HTTP requests received by the app"
)

@app.get("/")
def root():
    REQUEST_COUNT.inc()
    return {
        "service": "${{ values.name }}",
        "owner": "${{ values.owner }}",
        "environment": "dev",
        "created_by": "backstage-golden-path"
    }

@app.get("/health")
def health():
    return {"status": "ok"}

@app.get("/metrics")
def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)